# Используем Ubuntu 22.04 в качестве базового образа
FROM ubuntu:22.04

ENV TZ=Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# Обновление репозиториев
RUN apt-get update && apt-get -y install gpg && echo -n 'deb http://ppa.launchpad.net/ondrej/php/ubuntu groovy main' > /etc/apt/sources.list.d/ondrej-ubuntu-php-groovy.list && \
        apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 14AA40EC0831756756D7F66C4F4EA0AAE5267A6C
RUN apt-get update

RUN apt-get install -y software-properties-common && \
        add-apt-repository -y ppa:ondrej/php && \
        apt-get update

RUN apt-get install -y curl nano

# Установка необходимых пакетов: Nginx, PHP-FPM, и другие зависимости
RUN apt-get update && \
    apt-get install -y nginx php7.4-fpm php7.4-mysql php7.4-curl php7.4-gd php7.4-intl php7.4-mbstring php7.4-xml php7.4-zip && \
    mkdir -p /var/www/wp64

# Настройка PHP-FPM для создания сокета
RUN sed -i 's/^listen = .*/listen = \/var\/run\/php\/php7.4-fpm.sock/' /etc/php/7.4/fpm/pool.d/www.conf

RUN mkdir -p /var/run/php/

RUN apt-get install -y vsftpd

# Создание пользователя для FTP
RUN useradd -m -d /home/ftpuser ftpuser
RUN echo "ftpuser:password" | chpasswd

# Настройка vsftpd
RUN sed -i 's/anonymous_enable=YES/anonymous_enable=NO/g' /etc/vsftpd.conf
RUN echo "local_enable=YES" >> /etc/vsftpd.conf
RUN echo "write_enable=YES" >> /etc/vsftpd.conf
RUN echo "local_umask=022" >> /etc/vsftpd.conf
RUN echo "dirmessage_enable=YES" >> /etc/vsftpd.conf
RUN echo "xferlog_enable=YES" >> /etc/vsftpd.conf
RUN echo "connect_from_port_20=YES" >> /etc/vsftpd.conf
RUN echo "chroot_local_user=NO" >> /etc/vsftpd.conf
RUN echo "allow_writeable_chroot=NO" >> /etc/vsftpd.conf
RUN echo "chroot_list_enable=YES" >> /etc/vsftpd.conf
RUN echo "chroot_list_file=/etc/vsftpd.chroot_list" >> /etc/vsftpd.conf

# Создание директории для FTP
RUN mkdir -p /var/www/wp64
RUN chown -R ftpuser:ftpuser /var/www/wp64
RUN chmod 777 -R /var/www/wp64

# Указываем рабочую директорию
WORKDIR /var/www/wp64

# Открываем порты для Nginx
EXPOSE 80

# Запускаем Nginx и PHP-FPM при старте контейнера
CMD service vsftpd start && service nginx start && php-fpm7.4 -F